apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: web-app
    env: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
      env: web
  template:
    metadata:
      name: web-app
      labels:
        app: web-app
        env: web
    spec:
      containers:
      - name: web-container
        image: ganesh5124/docker-apps:25
        ports:
        - containerPort: 80